<?php

return [
    'allowed' => [
    	'businesscategory',
    	//'newsletter',
    	//'countries',
    	//'cities',
    	//'products',
    	'banners',
    	'home_images',
    	'cms',
    	'blogs_categories',
    	'blogs',
    	'images',
    	'videos',
    	//'events',
    	//'testimonials',
        'settings',
    	'news',
        'forms',
        'coupons',
        'users',
        'enquiries',
        'readymadeproducts',
        'category',
        //'collections',
        'orders',
        'vendors',
    ],
];